version: "3.8"

services:
  blockchain:
    build: ./blockchain
    volumes:
      - ./blockchain/artifacts:/app/artifacts  # Sync compiled contracts
    ports:
      - "8545:8545"

  backend:
    build: ./backend
    depends_on:
      - blockchain
    volumes:
      - ./blockchain/artifacts:/app/abi  # Copy ABI to backend
    environment:
      - BLOCKCHAIN_URL=http://blockchain:8545
    ports:
      - "3000:3000"
